#define IDR_MAINFRAME					128
#define IDD_WIN32APP_DIALOG				102
#define IDD_ABOUTBOX					103
#define IDS_APP_TITLE					103
#define IDM_ABOUT						104
#define IDM_EXIT						105
#define IDS_HELLO						106
#define IDI_WIN32APP	            	107
#define IDI_SMALL						108
#define IDC_WIN32APP	            	109
#define IDC_MYICON						2
#define IDC_STATIC	                    -1
